In [6]:
import numpy as np

In [7]:
data = np.random.randint(0,10,(3,3))
data

array([[1, 6, 1],
       [8, 6, 4],
       [5, 1, 2]], dtype=int32)

In [8]:
np.random.randn(3,10).mean()

np.float64(0.057289216350313275)

In [9]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [10]:
[Store ID, Sales, Customers, Inventory, Returns]

SyntaxError: invalid syntax (2577033590.py, line 1)

In [11]:
retail_data[:,1].sum() # we found total sales

np.int64(335000)

In [12]:
retail_data[:,3].argmax()+1 # we found position of highest inventory.

np.int64(9)

In [13]:
(retail_data[:,1]/retail_data[:,2]).argmax()+1

np.int64(1)

### Basic Performance Analysis

In [14]:
# 1. What is the **total revenue** generated across all stores?
tot_rev = retail_data[:,1].sum() * retail_data[:,3].sum()
tot_rev

np.int64(4790500000)

In [15]:
# 2. Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [16]:
# 3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [17]:
# 4. What is the **average daily sales** per store?
retail_data[:,1].sum() / 10

np.float64(33500.0)

In [23]:
# 5. How many stores achieved sales **above ₹35,000**?
data = (retail_data[:,1])
data[data > 35000]

array([41000, 39000, 45000])

### Customer Insights


In [25]:
# 6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

np.int64(9)

In [29]:
# 7. What is the **average number of customers** per store?
retail_data[:,2].mean()

np.float64(425.0)

In [32]:
# 8. How many stores have **more than 450 customers**?
dat = retail_data[:,2]
dat[dat>450]

array([500, 480, 550])

In [35]:
# 9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [62]:
# 10. Is there any store where **high sales do not correspond to high customers**?
sal = retail_data[:,1].mean()
cus = retail_data[:,2].mean()
mis = retail_data[(retail_data[:,1] > sal) & (retail_data[:,2] < cus)]
mis

array([[    5, 35000,   420,  1400,    12]])

### Inventory & Returns Analysis


In [64]:
# 11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [65]:
# 12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [69]:
# 13. How many stores have **inventory less than 1300 units**?
lowest_inve = retail_data[(retail_data[:,3]) < 1300]
lowest_inve

array([[    1, 25000,   300,  1200,    10],
       [    3, 28000,   380,  1100,     8],
       [    8, 30000,   400,  1250,    14]])

In [80]:
# 14. Which store has the **highest return rate** (returns ÷ inventory)?
ret_rate = (retail_data[:,4]) / (retail_data[:,3])
ret_rate.argmax()+1

np.int64(9)

In [84]:
# 15. Which stores have **returns greater than 15 units**?
ret = retail_data[(retail_data[:,4]) > 15]
ret

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

### Sales & customer Correlation

In [85]:
# 16. Is there a **positive correlation** between sales and customers?


In [86]:
# 17. Which store has **high customer visits but low sales**?
first = retail_data[:,2].mean()
sec = retail_data[:,1].mean()
res = retail_data[(retail_data[:,2] > first) & (retail_data[:,1] < sec)]
res

array([[    2, 32000,   450,  1500,    15]])

In [87]:
# 18. Which store has **low customers but high sales**?
first = retail_data[:,2].mean()
sec = retail_data[:,1].mean()
res = retail_data[(retail_data[:,2] < first) & (retail_data[:,1] > sec)]
res

array([[    5, 35000,   420,  1400,    12]])

In [115]:
# 19. How many stores have **sales per customer above ₹90**?
res = retail_data[:,1] / retail_data[:,2]
new = np.sum(res > 90)
new

np.int64(0)

In [116]:
# 20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?


### Profitability & Growth

In [117]:
# 21. If profit margin is **20% of sales**, what is the **profit per store**?
res = 0.20 * retail_data[:,1]
res

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [120]:
# 22. Which store has the **highest profit**?
(retail_data[:,1] * 0.20).argmax()+1

np.int64(9)

In [121]:
# 23. Which store has the **lowest profit**?
(retail_data[:,1] * 0.20).argmin()+1

np.int64(1)

In [126]:
# 24. If sales increase by **10% next month**, what are the **new sales figures**?
retail_data[:,1] * 0.10

array([2500., 3200., 2800., 4100., 3500., 2700., 3900., 3000., 4500.,
       3300.])

In [124]:
# 25. How will **total profit** change with the 10% sales increase?
(retail_data[:,1] * 0.10) + retail_data[:,1]

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

### Operational Strategy


In [130]:
# 26. Which stores need **inventory restocking** based on sales and current stock?
sal = retail_data[:,1].mean()
ret = retail_data[:,4].mean()
res = retail_data[(retail_data[:,1] > sal) & (retail_data[:,4] < ret)]
res

array([[    5, 35000,   420,  1400,    12]])

In [136]:
# 27. Which stores show **high returns percentage** and might require **quality checks**?
aver = retail_data[:,4].mean()
res = retail_data[(retail_data[:,4] > aver)]
res

array([[    2, 32000,   450,  1500,    15],
       [    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [138]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find best performer
best_index = np.argmax(overall_score)
best_store = retail_data[best_index]

print(f"Best performer overall: Store ID {int(best_store[0])}")
print(f"Sales: {best_store[1]}, Customers: {best_store[2]}, Inventory: {best_store[4]}")

Best performer overall: Store ID 9
Sales: 45000, Customers: 550, Inventory: 25


In [139]:
# 29. Which store is the **worst performer overall**?
inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find worst performer
worst_index = np.argmin(overall_score)
worst_store = retail_data[worst_index]

print(f"Worst performer overall: Store ID {int(worst_store[0])}")
print(f"Sales: {worst_store[1]}, Customers: {worst_store[2]}, Inventory: {worst_store[4]}")


Worst performer overall: Store ID 1
Sales: 25000, Customers: 300, Inventory: 10


In [142]:
# 30. Which stores can be considered for **expansion** based on strong sales and customer metrics?
a = retail_data[:,1].mean()
b = retail_data[:,2].mean()
res = retail_data[(retail_data[:,1] > a) & (retail_data[:,2] > b)]
res

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])